//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public decimal sr_no { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string user_name { get; set; }
        public string email_id { get; set; }
    }
}
