//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_box
    {
        public decimal sr_no { get; set; }
        public string from_mail { get; set; }
        public string to_mail { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
    }
}
